Code.require_file(Path.expand("../../../../web/test/test_helper.exs", __DIR__))
Code.require_file(Path.expand("../test/support/test_fixtures.ex", __DIR__))
Code.require_file(Path.expand("../../attendance/test/support/test_fixtures.ex", __DIR__))
Code.require_file(Path.expand("../../claims/test/support/test_fixtures.ex", __DIR__))
Code.require_file(Path.expand("../../leave/test/support/test_fixtures.ex", __DIR__))
Code.require_file(Path.expand("../../reference_data/test/support/test_fixtures.ex", __DIR__))
