defmodule Bilimbi.People.Skills.Action do
  @moduledoc false
  use Ecto.Schema

  schema "people_skill_actions" do
    field(:tenant_id, :integer)
    field(:company_id, :integer)
    field(:employee_id, :integer)
    field(:employee_name, :string)
    field(:skill_id, :integer)
    field(:source_assessment_id, :integer)
    field(:action_type_id, :integer)
    field(:starting_level, :integer)
    field(:target_level, :integer)
    field(:gap_at_start, :integer)
    field(:criticality, :string)
    field(:mandatory, :boolean)
    field(:priority_multiplier, :integer)
    field(:priority_score, :integer)
    field(:priority_explanation, :string)
    field(:manual_reason, :string)
    field(:objective, :string)
    field(:intervention, :string)
    field(:expected_evidence, :string)
    field(:owner_employee_id, :integer)
    field(:coordinator_employee_id, :integer)
    field(:provider_employee_id, :integer)
    field(:provider_name, :string)
    field(:start_on, :date)
    field(:due_on, :date)
    field(:status, :string)
    field(:closure, :string)
    field(:approved_by_user_id, :integer)
    field(:approved_at, :naive_datetime)
    field(:completed_at, :naive_datetime)
    field(:completion_evidence, :string)
    field(:reassessment_due_on, :date)
    field(:post_assessment_id, :integer)
    field(:post_level, :integer)
    field(:improvement, :integer)
    field(:next_steps, :string)
    field(:created_by_user_id, :integer)
    field(:request_key, :string)
    timestamps(type: :naive_datetime)
  end
end
